### PR TITLE
Tencent pulled the previous tag of their API and switched to `v1`

### LINKED ISSUE #31: tencentcloud dependency seems to be gone
Hello people,

I've just realized that this project depends on an unexpected version of `tencentcloud`: https://github.com/hashicorp/go-kms-wrapping/blob/master/go.mod#L33 :
```
github.com/tencentcloud/tencentcloud-sdk-go v3.0.171+incompatible
```

The tag `v3.0.171` in their repo seems to be [gone](https://github.com/TencentCloud/tencentcloud-sdk-go/tags). I can **still** build locally because I imagine `https://proxy.golang.org` still has the cached version.  However, it won't build using a configuration like this:

```
GOPROXY="direct"
```

So, I was wondering if you have plans for a new version `v0.6.2` using an existing tag for `tencentcloud`? 

BTW, I created a similar issue in [go-discover](https://github.com/hashicorp/go-discover/issues/172).

Thanks a lot

### PR DESCRIPTION
**Pull request by jeffwidman**
starting here: https://github.com/TencentCloud/tencentcloud-sdk-go#%E9%80%9A%E8%BF%87go-get%E5%AE%89%E8%A3%85%E6%8E%A8%E8%8D%90

As a result, currently `go get -d` is complaining in downstream repos,
breaking Dependabot (among other things).

So this fixes that.

Fix #31.

### CODE REVIEW

**Comment by jefferai** [comment]
Any particular reason you picked 162?

**Comment by jeffwidman** [comment]
Nope, it just happened to be the latest at the time I put up the PR.

**Comment by jefferai** [comment]
Thanks! I've merged and tagged.

**Comment by jeffwidman** [comment]
Thanks @jefferai! I really appreciate it.

The same problem is also breaking the builds of `hashicorp/go-discover` and I put up a PR fixing it here: https://github.com/hashicorp/go-discover/pull/173

Any chance you could take a look at that one as well? Or if that's another team internally, could you nudge an engineer on that team?

**Comment by jefferai** [comment]
@jeffwidman Honestly I've never touched go-discover so I'd rather the maintainers there handle that PR.

**Comment by jeffwidman** [comment]
Totally get it, and looks like the maintainers there did respond to me... I've been offline the past two weeks due to a new baby, and forgot about this til I saw your notification... I'll get that fixed over there pronto.

Thank you!

**Pull request merged**
