### PR TITLE
Work around an azure HTTP/2 bug

### PR DESCRIPTION
**Pull request by sgmiller**
Azure's client by default doesn't health check HTTP/2 keepalive conns, and instead lets the os close them after inactivity if they become unhealthy or are closed unexpectedly.  This can take 15 minutes.  If too many idle conns get hung in this state the client becomes unusable.  This workaround was provided by Microsoft as they investigate the issue.

Issue: https://github.com/Azure/azure-sdk-for-go/issues/21346
Workaround is frrom that issue but backported to the older Azure client.

### CODE REVIEW

**Review by jimlambrt — DISMISSED** [review]
It appears you forgot to add your unit test commits to the PR.  Would you mind adding them?

**Comment by sgmiller** [comment]
Unfortunately this can't be unit tested.  It relies on HTTP/2 connections being dropped on the Azure side, which is very intermittent.  The rest of the change is covered by the acceptance tests that existed already.

**Review by victorr — APPROVED** [review]
👍

**Review by victorr — APPROVED** [review]

**Comment by jimlambrt** [comment]
I'm a bit skeptical that the existing vault unit tests asserted anything about the custom transport you've added.  

I've pushed some unit tests which do some minimal assertions about the fix.

**Review by jefferai — APPROVED** [review]
Obviously this mostly relies on MSFT being correct in their given workaround but seems fine... any chance you have figured out a repeated way to trigger it to see if this actually helps?

**Comment by sgmiller** [comment]
Unfortunately no.  I might be able to do it with iptables but not great for unit testing.

**Comment by sgmiller** [comment]
> I'm a bit skeptical that the existing vault unit tests asserted anything about the custom transport you've added.
> 
> I've pushed some unit tests which do some minimal assertions about the fix.

Okay, that's a useful thing to verify.  Thanks.

**Pull request merged**
