### PR TITLE
Bump to oracle version using go modules

### PR DESCRIPTION
**Pull request by jeffwidman**
This bumps to the oracle version that uses go modules.

### CODE REVIEW

**Comment by jeffwidman** [comment]
@jefferai why was this closed w/o any explanation?

The `+incompatible` is going to cause difficulties in the go module ecosystem sooner or later... possibly making it hard to enable the upcoming lazy-loading in 1.17, although it's been a few months since I looked deeply into that so my memory is hazy on the details.

**Comment by jefferai** [comment]
@jeffwidman I didn't close it on purpose. I did change the default branch from `master` to `main`. GH was supposed to automatically update the PRs to point to the new branch -- the other two PRs both were updated successfully and it looks like yours was not for some reason and it got closed instead. I can't reopen the PR since it's against a branch that no longer exists. Can you re-open it against `main`?

Sorry for the trouble!

**Comment by jeffwidman** [comment]
Ah, that makes sense. Good thing I asked.

**Comment by jeffwidman** [comment]
It looks like I deleted my fork and that's why github reacted by auto-closing. I recreated it here: https://github.com/hashicorp/go-kms-wrapping/pull/37

**Pull request closed without merging**
